title: Mahdi2 Abolfazli Esfahani # your name (or website title) here
logo: "/images/mahdi4.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Ph.D. Candidate of EEE  
  <br><br>
  NTU, Singapore 
  <br><br>
  Trying to make robots intelligent 
  <br><br>
  <a href="https://www.linkedin.com/in/mahdi-abolfazli-esfahani-05332253/" target="_blank">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://scholar.google.com/citations?user=Y7pVVy4AAAAJ&hl=en&oi=ao/" target="_blank">View My Google Scholar</a> 
  <br><br>  
  <a href="https://twitter.com/abolfazli_mahdi/" target="_blank">Follow Me on Twitter</a> 
  <br><br>
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here

google_analytics: 
show_downloads: false
gems:
  - jekyll-mentions

